### ISSUE TITLE
TypeError: unsupported operand type(s) for |: 'type' and 'type'

### ISSUE THREAD

**Issue by Gade-Z** [dokkum/maskfill#4]
def process_masked_pixels(input_image : np.ndarray,
                           pad_width : int, 
                         mask : np.ndarray = None, 
--->                 operator_func : Callable[[np.ndarray|float], np.ndarray|float] = np.nanmean):

TypeError: unsupported operand type(s) for |: 'type' and 'type'

**Comment by Gade-Z** [comment]
When I import it shows this Error

**Comment by prappleizer** [comment]
Hi @Gade-Z  -- could you let me know which version of Python you are using? Note that the type annotations used in definitions for this code are only supported by recent versions of python, ~ version 3.7+, and the "|" operator is only supported by even more recent versions (I believe maybe 3.9 or 3.10?). 

If your version of python and numpy libraries are up to date, I will be happy to look further into this!

**Comment by Gade-Z** [comment]
> Hi @Gade-Z -- could you let me know which version of Python you are using? Note that the type annotations used in definitions for this code are only supported by recent versions of python, ~ version 3.7+, and the "|" operator is only supported by even more recent versions (I believe maybe 3.9 or 3.10?).
> 
> If your version of python and numpy libraries are up to date, I will be happy to look further into this!

Thank you! I have solved this problem by updating to the latest version of python.

**Comment by prappleizer** [comment]
Amazing! Happy to hear that. 

I'll close this issue then, but will endeavor to make a stronger note in the installation instructions which Python version is necessary. Thanks for trying out maskfill!
